name: Publish
on:
    release:
        types: [ published ]
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup JDK 16
                uses: actions/setup-java@v2
                with:
                    distribution: 'zulu'
                    java-version: '16'
            -   name: Grant Permissions to gradlew
                run: chmod +x gradlew
            -   name: Build with Gradle
                run: ./gradlew build
            -   name: Publish
                run: ./gradlew publish
                env:
                    JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
                    JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
